services:
  database:
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - internal

  backend:
    build:
      context: ./backend
    environment:
      PORT: 3000
      DB_HOST: database
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    ports:
      - '3000:3000'
    depends_on:
      - database
    networks:
      - internal

volumes:
  db_data:

networks:
  internal:
